-- Seed file: paste into Supabase SQL Editor → Run
-- Safe to run multiple times (uses ON CONFLICT DO NOTHING)

-- ── Clients ───────────────────────────────────────────────────────────────────
INSERT INTO clients (id, name, email, phone, company, service_type, tags, notes, last_contact_date, created_at) VALUES
  ('aaaaaaaa-0001-0001-0001-000000000001', 'Priya Sharma',    'priya@interiorsbypriya.com', '+91 98765 43210', 'Interiors by Priya',        'Interior Design Consultation',  ARRAY['active','high-value','referral'], 'Specialises in luxury residential interiors in South Delhi. Very responsive over WhatsApp. Referred two clients already. Interested in a retainer package.',                      '2026-04-15', '2025-10-01'),
  ('aaaaaaaa-0002-0002-0002-000000000002', 'Arjun Mehta',     'arjun.mehta@studioarjun.in', '+91 91234 56789', 'Studio Arjun',              'Architectural Visualization',    ARRAY['active','vip'],                  'Award-winning architect focusing on sustainable buildings in Mumbai. Needs monthly check-ins. Potential for large project collaboration in Q3.',                                    '2026-05-01', '2025-11-15'),
  ('aaaaaaaa-0003-0003-0003-000000000003', 'Kavya Nair',      'kavya@nairdesigns.com',      '+91 99887 76655', 'Nair Designs',              'Brand Identity & Packaging',     ARRAY['inactive','follow-up'],          'Freelance graphic designer from Bangalore. Was very engaged initially but went quiet after onboarding. Needs a re-engagement message.',                                           '2026-02-20', '2025-09-10'),
  ('aaaaaaaa-0004-0004-0004-000000000004', 'Rohit Verma',     'rohit.v@vermaandco.com',     NULL,              'Verma & Co. Architects',    'Commercial Interior Design',     ARRAY['prospect','new'],                'Recently connected at Delhi Design Week. Showed interest in our marketing services. Follow up on the proposal sent last week. Has a team of 15 architects.',                     NULL,         '2026-05-10'),
  ('aaaaaaaa-0005-0005-0005-000000000005', 'Meera Iyer',      'meera@meeraiyer.studio',     '+91 98001 23456', 'Meera Iyer Studio',         'Home Staging & Photography',     ARRAY['active','new'],                  'Runs a boutique home staging business in Chennai. Very active on Instagram. Open to co-creating content for social media. Strong long-term collaboration potential.',             '2026-05-20', '2026-01-05'),
  ('aaaaaaaa-0006-0006-0006-000000000006', 'Siddharth Bose',  'sid@bosearchitects.co.in',   '+91 70123 45678', 'Bose Architects',           'Urban Planning Consultancy',     ARRAY['churned','inactive'],            'Engaged for 6 months but did not renew due to budget cuts. Good working relationship overall. Consider a soft re-engagement in 3 months.',                                       '2025-12-01', '2025-07-20')
ON CONFLICT (id) DO NOTHING;

-- ── Message Logs ──────────────────────────────────────────────────────────────
INSERT INTO message_logs (id, client_id, message_type, draft_content, sent_status, created_at) VALUES
  ('bbbbbbbb-0001-0001-0001-000000000001', 'aaaaaaaa-0001-0001-0001-000000000001', 'check-in',      'Hi Priya! Just checking in — hope the Vasant Vihar project is going smoothly. I had a few content ideas for your Instagram that could showcase the before-and-after transformation. Would love to connect this week if you have time!', 'sent',  '2026-04-15'),
  ('bbbbbbbb-0002-0002-0002-000000000002', 'aaaaaaaa-0003-0003-0003-000000000003', 're-engagement', 'Hey Kavya, it''s been a while! I''ve been following your work on Instagram and the packaging you did for that organic skincare brand was stunning. I wanted to reach out because I have a new service that might be perfect for freelancers like you. Can we hop on a quick call?', 'draft', '2026-05-10'),
  ('bbbbbbbb-0003-0003-0003-000000000003', 'aaaaaaaa-0002-0002-0002-000000000002', 'upsell',        'Hi Arjun, I hope the Bandra project is going well! I wanted to share an exciting new offering — a monthly content strategy package specifically designed for architects and designers. Given your incredible portfolio, I think we could position Studio Arjun as a thought leader in sustainable architecture. Happy to share a proposal?', 'draft', '2026-05-05')
ON CONFLICT (id) DO NOTHING;

-- ── Follow-Up Schedule ────────────────────────────────────────────────────────
INSERT INTO follow_up_schedule (id, client_id, reminder_date, follow_up_status, notes, created_at) VALUES
  ('cccccccc-0001-0001-0001-000000000001', 'aaaaaaaa-0003-0003-0003-000000000003', '2026-05-25', 'pending',   'Send re-engagement email — check if she has any upcoming projects we can help with.',         '2026-05-01'),
  ('cccccccc-0002-0002-0002-000000000002', 'aaaaaaaa-0004-0004-0004-000000000004', '2026-05-30', 'pending',   'Follow up on the proposal shared at Delhi Design Week. Ask if he has reviewed the pricing.', '2026-05-12'),
  ('cccccccc-0003-0003-0003-000000000003', 'aaaaaaaa-0001-0001-0001-000000000001', '2026-06-15', 'pending',   'Discuss retainer package renewal. Priya mentioned she is planning a major project in July.',  '2026-05-15'),
  ('cccccccc-0004-0004-0004-000000000004', 'aaaaaaaa-0002-0002-0002-000000000002', '2026-06-01', 'pending',   'Monthly check-in call with Arjun. Review content performance for the past month.',           '2026-05-01'),
  ('cccccccc-0005-0005-0005-000000000005', 'aaaaaaaa-0006-0006-0006-000000000006', '2026-08-01', 'snoozed',   'Soft re-engagement for Siddharth after 3-month cooling period. Budget might be better.',      '2026-05-01')
ON CONFLICT (id) DO NOTHING;

-- ── Content Calendar ──────────────────────────────────────────────────────────
INSERT INTO content_calendar (id, post_type, draft_content, topic, scheduled_date, status, created_at) VALUES
  ('dddddddd-0001-0001-0001-000000000001', 'instagram',  'Transforming spaces, one project at a time ✨ Swipe to see our latest luxury residential interior in South Delhi. Every corner tells a story. What''s your dream room? Drop it in the comments! #InteriorDesign #LuxuryLiving #DelhiHomes #DesignInspiration', 'Luxury Interior Reveal',     '2026-06-02', 'scheduled', '2026-05-20'),
  ('dddddddd-0002-0002-0002-000000000002', 'linkedin',   'Sustainable architecture isn''t just a trend — it''s the future. At Studio Arjun, we''ve been integrating passive cooling systems and locally sourced materials into every project for the past 5 years. Here''s what we learned: 1. Client education is 80% of the job. 2. Local materials reduce costs AND carbon footprint. 3. The ROI of sustainable buildings is now measurable. What sustainable features are you incorporating into your projects?', 'Sustainable Architecture Insights', '2026-06-03', 'scheduled', '2026-05-21'),
  ('dddddddd-0003-0003-0003-000000000003', 'blog',       'The freelance design market in India is booming — but standing out requires more than great work. In this guide, we break down the 5 marketing strategies that top Indian designers are using to build 6-figure client pipelines without paid advertising. From leveraging WhatsApp to using Instagram Reels strategically, these tactics are proven to work in the Indian market.', 'Marketing for Indian Designers', '2026-06-05', 'draft',     '2026-05-18'),
  ('dddddddd-0004-0004-0004-000000000004', 'newsletter', 'Hello design community! This month we are diving into: → How home staging increased this Chennai property''s sale price by 18% → 3 Instagram trends interior designers should be using in Q3 → Behind the scenes: our process for creating a complete brand identity in 2 weeks. Read to the end for an exclusive discount on our new content strategy package!', 'June Design Newsletter',        '2026-06-08', 'scheduled', '2026-05-22'),
  ('dddddddd-0005-0005-0005-000000000005', 'instagram',  'Before & After: Can you believe this is the same room? 🏠➡️✨ Our client wanted a home office that felt like a luxury hotel suite. We used warm neutrals, custom joinery, and carefully curated lighting to transform this space. The secret? Layers. Light, texture, and height create depth that photographs love. Save this for your next project! #HomeOffice #BeforeAndAfter #InteriorTransformation', 'Home Office Transformation',    '2026-06-10', 'draft',     '2026-05-19'),
  ('dddddddd-0006-0006-0006-000000000006', 'twitter',    'Hot take: Most interior designers are leaving 40% of their potential clients on the table by not having a clear content strategy. Your portfolio is beautiful. But if it''s only living on Houzz, you''re invisible to 90% of your ideal clients. Instagram, LinkedIn, and a weekly email = the triangle of consistent client acquisition. Fight me. 👇', 'Content Strategy Hot Take',     '2026-06-12', 'draft',     '2026-05-20')
ON CONFLICT (id) DO NOTHING;

-- ── Content Library ───────────────────────────────────────────────────────────
INSERT INTO content_library (id, title, content, category, tags, performance_notes, use_count, created_at) VALUES
  ('eeeeeeee-0001-0001-0001-000000000001', 'Re-Engagement: The Soft Nudge',         'Hi [Name], it''s been a while! I was thinking about you when I came across [specific project/achievement related to their work]. I wanted to reach out because I''ve been working on something that I think would be genuinely valuable for [their business type]. Would you be open to a quick 15-minute chat this week? No pitch, just an update and to hear how things are going for you!',                                                                                   'outreach',  ARRAY['re-engagement','warm-lead','WhatsApp'],                  'Best sent on Tuesday or Wednesday mornings. 68% reply rate when personalised with a specific recent achievement.',  12, '2025-11-01'),
  ('eeeeeeee-0002-0002-0002-000000000002', 'Instagram Caption: Project Reveal',     'Swipe to see the full transformation ✨ [Brief project description — 1 sentence]. Every design decision was intentional: [Highlight 3 key design choices]. The result? A space that [emotional outcome for the client]. What do you think — which before or after is your favourite? Drop it below! 👇 [4-6 hashtags relevant to the project]',                                                                                                    'social',    ARRAY['instagram','caption','reveal','engagement'],             '30% higher engagement than standard captions. The question at the end drives 3x more comments.',                   8,  '2025-12-10'),
  ('eeeeeeee-0003-0003-0003-000000000003', 'Monthly Check-In Email',                'Subject: Quick check-in from [Your Name]\n\nHi [Name],\n\nHope [month] is treating you well! I wanted to check in and see how [their current project/goal] is progressing.\n\nI''ve been thinking about our last conversation and had a few ideas that might be relevant for you:\n• [Idea 1 specific to their business]\n• [Idea 2]\n\nWould love to catch up — are you free for a quick 20-minute call [suggest 2 time slots]?\n\nWarm regards,\n[Your Name]', 'email',     ARRAY['check-in','monthly','relationship','email'],             'Reply rate of 45% when time slots are included. Personalisation with their current project is key.',               15, '2025-10-15'),
  ('eeeeeeee-0004-0004-0004-000000000004', 'LinkedIn Thought Leadership Post',      'I''ve worked with 50+ [industry] professionals over the past [X] years, and the ones who build the most successful businesses all share one thing:\n\nThey treat their personal brand as a business asset, not an afterthought.\n\nHere''s the 3-part framework they use:\n\n1️⃣ [Framework step 1 — specific and actionable]\n2️⃣ [Framework step 2]\n3️⃣ [Framework step 3]\n\nThe result? [Specific outcome — more clients, higher rates, etc.]\n\nWhat would you add to this list? I''d love to hear your perspective. 👇', 'social',    ARRAY['linkedin','thought-leadership','framework','engagement'], 'Posts with numbered lists and a question get 4x more comments. Best day to post: Tuesday 8-9am.',                  6,  '2026-01-05'),
  ('eeeeeeee-0005-0005-0005-000000000005', 'Upsell: New Service Intro',             'Hi [Name],\n\nI hope [project they are working on] is going brilliantly! I wanted to share something exciting that I think would be a great fit for where [their business] is right now.\n\nWe''ve just launched [New Service Name] — a [brief description] designed specifically for [their business type].\n\nIn a nutshell, it helps you:\n✓ [Benefit 1]\n✓ [Benefit 2]\n✓ [Benefit 3]\n\nGiven [specific thing about their business], I think this could [specific outcome] for you. I''d love to share a quick proposal — would you have 20 minutes this week?\n\nLooking forward to it!',                                                     'outreach',  ARRAY['upsell','new-service','proposal','email'],               NULL,                                                                                                                2,  '2026-02-20'),
  ('eeeeeeee-0006-0006-0006-000000000006', 'Referral Request Template',             'Hi [Name],\n\nIt''s been such a pleasure working with you on [project/service]. Seeing [specific result or transformation] has been genuinely rewarding!\n\nI''m growing my client base and would love to work with more people like you. If you know any [ideal client description] who might benefit from [your service], I''d be so grateful for an introduction.\n\nOf course, no pressure at all — and if anyone comes to mind, even a quick "you should speak to [Your Name]" goes a long way.\n\nThank you again for being such a wonderful client!\n\nWarm regards,\n[Your Name]',                                                                   'outreach',  ARRAY['referral','warm','relationship','email'],                'Best sent 2-3 weeks after a successful project delivery. 3 out of 5 clients respond positively.',                  9,  '2026-01-20')
ON CONFLICT (id) DO NOTHING;
